// app/lib/seoMetadata.ts
export interface PageMetadata {
    title: string;
    description: string;
    keywords: string;
    ogTitle: string;
    ogDescription: string;
    ogImage: string;
    ogUrl: string;
    ogType: string;
    twitterCard: string;
    twitterTitle: string;
    twitterDescription: string;
    twitterImage: string;
}

export const SEO_CONFIG: Record<string, PageMetadata> = {
    home: {
        title: 'Sundara Moorthy - Strategy & Growth Advisor | Design Thinking Practitioner',
        description: 'Sundara Moorthy, Strategy & Growth Advisor | Design Thinking Practitioner',
        keywords: 'Risva Technologies, global software company, web development, mobile app development, AI solutions, React, Next.js, Node.js, Laravel, Express, PostgreSQL, MySQL, affordable development, rapid development, IT services India',
        ogTitle: 'Risva Technologies – Web, Mobile & AI Solutions',
        ogDescription: 'Affordable, fast and modern web, mobile & AI development services for global clients.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/',
        ogType: 'website',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Risva Technologies – Web, Mobile & AI Solutions',
        twitterDescription: 'Leading global development company for web, mobile & AI.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    about: {
        title: 'About Risva Technologies – Global Software, Web & AI Development',
        description: 'Learn about Risva Technologies, a global IT company offering affordable and rapid development for web, mobile & AI solutions using modern technologies.',
        keywords: 'About Risva Technologies, IT company India, global software development, tech company, AI development team, web experts, React developers, Node.js developers',
        ogTitle: 'About Risva Technologies',
        ogDescription: 'A global software and AI development company working with the latest technologies.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/about',
        ogType: 'article',
        twitterCard: 'summary_large_image',
        twitterTitle: 'About Risva Technologies',
        twitterDescription: 'We provide global web, mobile & AI development services.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    ai: {
        title: 'AI Solutions – Automation, Chatbots & Custom AI Apps',
        description: 'Risva Technologies delivers custom AI applications, automation tools, chatbots and intelligence systems for global businesses.',
        keywords: 'AI solutions, AI development, machine learning apps, automation systems, AI chatbots, custom AI development, Risva Technologies AI services',
        ogTitle: 'AI Solutions – Risva Technologies',
        ogDescription: 'Custom AI apps, automation and chatbots for businesses.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/ai-solutions',
        ogType: 'article',
        twitterCard: 'summary_large_image',
        twitterTitle: 'AI Solutions by Risva Technologies',
        twitterDescription: 'Powerful AI applications and automation tools.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    web: {
        title: 'Web App Development – React, Next.js, Node Experts',
        description: 'Build modern, secure web apps with Risva Technologies. Experts in React, Next.js, Node.js, Express, PHP & Laravel. Affordable global development services.',
        keywords: 'web app development, React development, Next.js experts, Node.js developers, PHP, Laravel development, custom web apps, Risva Technologies',
        ogTitle: 'Web App Development – Risva Technologies',
        ogDescription: 'Modern, scalable and secure web applications for global businesses.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/web-apps',
        ogType: 'article',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Web App Development – Risva Technologies',
        twitterDescription: 'Experts in React, Next.js, Node.js, Laravel.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    mobile: {
        title: 'Mobile App Development – Android & iOS Apps',
        description: 'We build high-performance Android & iOS apps using React with powerful Node.js or Laravel backends.Fast delivery, global support, affordable pricing.',
        keywords: 'mobile app development, Android apps, iOS apps, React Native development, mobile developers, app development India, Risva Technologies',
        ogTitle: 'Mobile App Development – Risva Technologies',
        ogDescription: 'Powerful and fast Android/iOS mobile app development.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/mobile-apps',
        ogType: 'article',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Mobile App Development – Risva Technologies',
        twitterDescription: 'We build modern Android and iOS apps.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    portfolio: {
        title: 'Portfolio – Web, Mobile & AI Projects – Risva Technologies',
        description: 'Explore our completed projects across web apps, mobile apps, and AI solutions for global clients.',
        keywords: 'portfolio, case studies, completed projects, web projects, mobile app portfolio, AI projects, Risva Technologies work',
        ogTitle: 'Portfolio – Risva Technologies',
        ogDescription: 'Our successful global projects in web, mobile and AI development.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/portfolio',
        ogType: 'website',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Portfolio – Risva Technologies',
        twitterDescription: 'See our web, mobile & AI works.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    contact: {
        title: 'Contact Risva Technologies – Hire Web, Mobile & AI Developers',
        description: 'Contact Risva Technologies for software, web, mobile app & AI solutions. Global support with fast and affordable development.',
        keywords: 'contact Risva Technologies, hire developers, web developers India, mobile app developers, AI developers, software support',
        ogTitle: 'Contact Risva Technologies',
        ogDescription: 'Reach out for IT, web, mobile and AI services.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/contact',
        ogType: 'website',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Contact Risva Technologies',
        twitterDescription: 'Hire expert developers for global projects.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    blog: {
        title: 'Tech Blog – Web, Mobile & AI Insights – Risva Technologies',
        description: 'Latest articles on web development, mobile apps, AI tools, React, Next.js, Node.js, software trends and business technology.',
        keywords: 'tech blog, web development blog, AI blog, React tutorials, Node.js articles, technology news, Risva Technologies blog',
        ogTitle: 'Tech Blog – Risva Technologies',
        ogDescription: 'Insights on AI, web and mobile development.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/blog',
        ogType: 'blog',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Tech Blog – Risva Technologies',
        twitterDescription: 'Read the latest tech insights and tutorials.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    webspeed: {
        title: 'Website Speed Optimization Services | Better SEO',
        description: 'Professional website speed optimization to improve loading time, Core Web Vitals, SEO rankings, and user experience across all devices.',
        keywords: 'website speed optimization, page speed services, improve website performance, core web vitals optimization, website loading speed.',
        ogTitle: 'Website Speed Optimization Services | Better SEO',
        ogDescription: 'Professional website speed optimization to improve loading time, Core Web Vitals, SEO rankings, and user experience across all devices.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/website-speed-optimization',
        ogType: 'webspeed',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Website Speed Optimization Services | Better SEO',
        twitterDescription: 'Professional website speed optimization to improve loading time, Core Web Vitals, SEO rankings.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    webmaintenance: {
        title: 'Website Maintenance Services, Keep Your Website Secure, Reliable',
        description: 'Reliable website maintenance services to keep your site secure, updated, fast, and running smoothly without downtime.',
        keywords: 'tech blog, web development blog, AI blog, React tutorials, Node.js articles, technology news, Risva Technologies blog',
        ogTitle: 'Website Maintenance Services, Keep Your Website Secure, Reliable',
        ogDescription: 'Reliable website maintenance services to keep your site secure, updated, fast, and running smoothly without downtime.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/website-maintenance',
        ogType: 'webmaintenance',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Website Maintenance Services, Keep Your Website Secure, Reliable',
        twitterDescription: 'Reliable website maintenance services to keep your site secure, updated, fast, and running smoothly without downtime.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    cmsvswordpress: {
        title: 'Hybrid CMS vs WordPress: Speed, Security, SEO & Scalability',
        description: ' Compare Hybrid CMS vs WordPress for speed, security, SEO, scalability, and long-term growth. Find out which CMS is best for modern business websites.',
        keywords: 'hybrid cms vs wordpress, wordpress vs modern cms, hybrid cms advantages, wordpress limitations, best cms for business website, headless cms vs wordpress, modern cms comparison',
        ogTitle: 'Hybrid CMS vs WordPress: Speed, Security, SEO & Scalability',
        ogDescription: 'Compare Hybrid CMS vs WordPress for speed, security, SEO, scalability, and long-term growth. Find out which CMS is best for modern business websites.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/hybrid-cms-vs-wordpress',
        ogType: 'cmsvswordpress',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Hybrid CMS vs WordPress: Speed, Security, SEO & Scalability',
        twitterDescription: 'Compare Hybrid CMS vs WordPress for speed, security, SEO, scalability, and long-term growth.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    seofriendly: {
        title: 'SEO-First Website Development – Dominate Google Search',
        description: 'We design SEO-friendly websites that load fast, rank better on Google, and convert visitors into customers using modern UI, UX, and clean code.',
        keywords: 'seo friendly website design, website design for seo, seo optimized web design, google friendly website, technical seo web design, fast loading website design',
        ogTitle: 'SEO-First Website Development – Dominate Google Search',
        ogDescription: 'We design SEO-friendly websites that load fast, rank better on Google, and convert visitors into customers using modern UI, UX, and clean code..',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/seo-friendly-website-design',
        ogType: 'seofriendly',
        twitterCard: 'summary_large_image',
        twitterTitle: 'SEO-First Website Development – Dominate Google Search',
        twitterDescription: 'We design SEO-friendly websites that load fast, rank better on Google, and convert visitors into customers using modern UI, UX, and clean code.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    reactnext: {
        title: 'Next.js & React Development for Fast, SEO-Ready Websites',
        description: 'We build high-performance websites using React and Next.js that are fast, secure, scalable, and optimized for SEO and business growth.',
        keywords: 'react website development, nextjs website development, react js web development company, next js developers, modern web app development, frontend development services',
        ogTitle: 'Next.js & React Development for Fast, SEO-Ready Websites',
        ogDescription: 'We build high-performance websites using React and Next.js that are fast, secure, scalable, and optimized for SEO and business growth.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/nextjs-website-design',
        ogType: 'reactnext',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Next.js & React Development for Fast, SEO-Ready Websites',
        twitterDescription: 'We build high-performance websites using React and Next.js that are fast, secure, scalable, and optimized for SEO and business growth.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    boostsales: {
        title: 'Web Design for Sales: Build Your Lead Generation Machine',
        description: 'We design conversion-focused websites that build trust, improve user experience, and turn visitors into leads and customers.',
        keywords: 'website to boost sales, conversion focused web design, high converting website, website for lead generation, sales driven website design, cro web design',
        ogTitle: 'Web Design for Sales: Build Your Lead Generation Machine',
        ogDescription: 'We design conversion-focused websites that build trust, improve user experience, and turn visitors into leads and customers.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/website-design-to-boost-sales',
        ogType: 'boostsales',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Web Design for Sales: Build Your Lead Generation Machine',
        twitterDescription: 'We design conversion-focused websites that build trust, improve user experience, and turn visitors into leads and customers.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    hosur: {
        title: 'Web Design Company in Hosur – Professional Website Designers for Business',
        description: 'Looking for a web design company in Hosur? We build fast, modern, SEO-friendly websites that help businesses get more leads and customers..',
        keywords: 'web design company in hosur, website designers in hosur, web development company hosur, hosur web designers, business website design hosur',
        ogTitle: 'Web Design Company in Hosur – Professional Website Designers for Business',
        ogDescription: 'Looking for a web design company in Hosur? We build fast, modern, SEO-friendly websites that help businesses get more leads and customers.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/web-design-company-hosur',
        ogType: 'hosur',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Web Design Company in Hosur – Professional Website Designers for Business',
        twitterDescription: 'Looking for a web design company in Hosur? We build fast, modern, SEO-friendly websites that help businesses get more leads and customers.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    bangalore: {
        title: 'Web Design Company in Bangalore – Modern, SEO & Business Focused Websites',
        description: 'Top web design company in Bangalore offering modern, fast, and SEO-optimized websites for startups, companies, and growing businesses.',
        keywords: 'web design company in bangalore, website designers in bangalore, web development company bangalore, bangalore web agency, business website design bangalore',
        ogTitle: 'Web Design Company in Bangalore – Modern, SEO & Business Focused Websites',
        ogDescription: 'Top web design company in Bangalore offering modern, fast, and SEO-optimized websites for startups, companies, and growing businesses.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/web-design-company-bangalore',
        ogType: 'bangalore',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Web Design Company in Bangalore – Modern, SEO & Business Focused Websites',
        twitterDescription: 'Top web design company in Bangalore offering modern, fast, and SEO-optimized websites for startups, companies, and growing businesses.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    tamilnadu: {
        title: 'Web Design Company in Tamilnadu – Professional Websites for Growing Businesses',
        description: 'We are a leading web design company in Tamilnadu building fast, SEO-friendly, and conversion-focused websites for all types of businesses.',
        keywords: 'web design company in tamilnadu, website designers tamilnadu, web development company tamilnadu, tamilnadu web design services, business website design tamilnadu.',
        ogTitle: 'Web Design Company in Tamilnadu – Professional Websites for Growing Businesses',
        ogDescription: 'We are a leading web design company in Tamilnadu building fast, SEO-friendly, and conversion-focused websites for all types of businesses.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/web-design-company-tamilnadu',
        ogType: 'tamilnadu',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Web Design Company in Tamilnadu – Professional Websites for Growing Businesses',
        twitterDescription: 'We are a leading web design company in Tamilnadu building fast, SEO-friendly, and conversion-focused websites for all types of businesses.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
    hybridcms: {
        title: 'Hybrid CMS: Fast, Secure & Scalable Websites',
        description: 'Build faster, more secure, and scalable websites using Hybrid CMS. Perfect for business websites, SaaS platforms, and high-performance applications.',
        keywords: 'hybrid cms, modern cms platform, headless hybrid cms, api driven cms, scalable cms for business, cms for saas, enterprise cms solution',
        ogTitle: 'Hybrid CMS: Fast, Secure & Scalable Websites',
        ogDescription: 'Build faster, more secure, and scalable websites using Hybrid CMS. Perfect for business websites, SaaS platforms, and high-performance applications.',
        ogImage: 'https://www.risva.app/favicon.ico',
        ogUrl: 'https://www.risva.app/hybrid-customized-cms-website',
        ogType: 'hybridcms',
        twitterCard: 'summary_large_image',
        twitterTitle: 'Hybrid CMS: Fast, Secure & Scalable Websites',
        twitterDescription: 'Build faster, more secure, and scalable websites using Hybrid CMS. Perfect for business websites, SaaS platforms, and high-performance applications.',
        twitterImage: 'https://www.risva.app/favicon.ico',
    },
} as const;

export type PageKey = keyof typeof SEO_CONFIG;